[user]
name = "$NAME"
email = "$EMAIL"
username = "$NICKNAME"

[init]
defaultBranch = "main"

[pull]
rebase = true

[fetch]
prune = true

[core]
editor = "nvim"
whitespace = "fix,-indent-with-non-tab,trailing-space,cr-at-eol"
quotepath = false

[credential]
helper = "cache --timeout 1800"

[commit]
template = "$TEMPLATE_PATH"

[color]
_ui = "auto"
_diff = "auto"
_status = "auto"
_branch = "auto"

[color.status]
added = "green"
changed = "yellow"
untracked = "red"

[color.branch]
current = "green"
local = "yellow"
remote = "red"

[color.diff]
meta = "yellow bold"
frag = "magenta bold"
old = "red bold"
new = "green bold"
whitespace = "red reverse"
