live_config_reload = true
ipc_socket = true

[window]
    opacity = 0.86
    blur = true
    title = ""
    dynamic_title = false

[font]
    size = 10.89
    normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
